### ISSUE TITLE
[FR] Add XML As Report Output Format Option

### ISSUE THREAD

**Issue by harrislance** [senseexcel/senseexcel-reporting#28]
please test it "spreadsheet"

**Comment by konne** [comment]
@harrislance  please can you describe more what you want. For XMLs are no general rule.
Do you just want the data like as CSV as XML? 
When we could even make add JSON.

**Comment by AlexanderGoerlich** [comment]
wont fix

**Comment by AlexanderGoerlich** [comment]
@konne : i want have a new discuss about these export format!
