### ISSUE TITLE
Table with TotalRow

### ISSUE THREAD

**Issue by ChristofHoldschick** [senseexcel/senseexcel-reporting#31]
Problem:
if a Totalrow is activated for a Table
then, after setting Selection, the Total-Row gets overriden by the Last Row of the Table.

Solution:
Before SE fills a Table it deactivates the TotalRow (if active) and activate it afterwards.

See also 
https://github.com/senseexcel/senseexcel/issues/36  <-- link to Excel totalrow doku inside!
https://github.com/senseexcel/senseexcel/issues/81

**Comment by mossbeard** [comment]
is fixed
