### ISSUE TITLE
Sheetloop contents special characters not possible

### ISSUE THREAD

**Issue by rgroschwitz** [senseexcel/senseexcel-reporting#41]
Sheetloop over field contents which contain special characters not possible (here for example ":").
Occurs with output format XLSX & PDF.
![sloopwhithspezail](https://user-images.githubusercontent.com/33517782/50832054-4dc9ef80-134d-11e9-94f9-d8df3b75a132.PNG)

**Comment by mossbeard** [comment]
Is fixed
