### ISSUE TITLE
SLoop text greater than n characters

### ISSUE THREAD

**Issue by rgroschwitz** [senseexcel/senseexcel-reporting#42]
If the SLoop text is greater than n characters, the first loop element is "swallowed" (see picture in red). In the "Total" sheet, on the other hand, the amonut is output from the missing sheet 3102 (see picture highlighted in yellow). Occurs with output format XLSX & PDF.
![issue](https://user-images.githubusercontent.com/33517782/50832158-a3060100-134d-11e9-93ac-c70d097e8617.PNG)

**Comment by rgroschwitz** [comment]
[SLoop_LongText.zip](https://github.com/senseexcel/senseexcel-reporting/files/2736824/SLoop_LongText.zip)

**Comment by mossbeard** [comment]
Is fixed
