### ISSUE TITLE
no valid json in result of SER.STATUS when status reaches 3 (ready)

### ISSUE THREAD

**Issue by ChristofHoldschick** [senseexcel/senseexcel-reporting#45]
when a report-generation has finshed, the result can be fetched with a call of SER.STATUS.
this returns a non valid json:
```
{
	"status":3,
	"log":"Delivery Report, Please wait...",
	"distribute":"{\r\n  \"hubResults\": [\r\n    {\r\n      \"link\": \"/sharedcontent/a07b6c79-15bd-4abf-ad1b-a4f1dac9dee5/0e8e072b-37ec-42f4-b115-6aca44d7e42a.pdf\",\r\n      \"success\": true,\r\n      \"message\": \"Upload Preview_c49064d7-3625-41da-b98b-cb0f63ad0f2b (PDF) successfully.\",\r\n      \"reportName\": \"Preview_c49064d7-3625-41da-b98b-cb0f63ad0f2b.pdf\"\r\n    }\r\n  ],\r\n  \"fileResults\": [],\r\n  \"mailResults\": []\r\n}"
}  
```

the call was made via the qlik.net SDK (.net 4.5.2) like so:
``` App.EvaluateExAsync()```
with the following parameterstring
```SER.STATUS('{"taskId":"e5582178-d2c5-4e97-80c2-5199615b3ef6"}'))  ```

**Comment by thomashaenig** [comment]
closed with https://github.com/q2g/ser-engine/commit/d98cd3d94b2ca235997f27ca34396ca1e42a18e8
