### ISSUE TITLE
Problems processing selections with space in their name (e.g. "Audit Fees")

### ISSUE THREAD

**Issue by ChristofHoldschick** [senseexcel/senseexcel-reporting#46]
if you run SER.START with a selection that contais spaces 
```
SER.START('                
                    ...
                        selections:
                        [
                            {
                              type: static
                               name: AccountDesc
                                values: ["Audit Fees"]
                             }                            
                        ]
                    }   
... 
```
some sort of a 'like search' seems to hapen
because in the resulting report not only 'Audit Fees' is selected but also 'Professional Fees'.
All Values containig 'Audit' and all Values containig 'Fees' are selected.

If i start ser.start with following modified selection:
```
SER.START('                
                    ...
                        selections:
                        [
                            {
                              type: static
                               name: AccountDesc
                                values: ["Fees"]
                             }                            
                        ]
                    }   
... 
```
then in the resulting report 'Audit Fees' and 'Professional Fees' is selected

**Comment by ChristofHoldschick** [comment]
found it, you have to wrap the items of the values array with single quotes '

**Comment by ChristofHoldschick** [comment]
you have to wrap te value with sinqle quote
```
                        selections:
                        [
                            {
                              type: static
                               name: AccountDesc
                                values: ["'Audit Fees'"]
                             }                            
                        ]
                    }   
```
or if used in a already wraped string (like SER.START('...')) use ```& chr(39 & ```

**Comment by ChristofHoldschick** [comment]
turns out that ```'Audit Fees'``` filters nothing
only ```"Audit Fees"``` is working in a Qlik-Listbox.
But to use this in an Ser.Start json it has to look like:
```
 selections:
                        [
                            {
                              type: static
                               name: AccountDesc
                                values: [""Audit Fees""]
                             }                            
                        ]
```
but SER can't handle two double qoutes

So ATM there is no way to use filtervalues, witch contains spaces, correctly

**Comment by ChristofHoldschick** [comment]
you have to set a star (*) at the end or beginning of the value
```
 selections:
                        [
                            {
                              type: static
                               name: AccountDesc
                                values: ["Audit Fees*"]
                             }                            
                        ]
```

**Comment by konne** [comment]
@ChristofHoldschick the * at the end has a differrent effect. This is NOT solving this issue, it just works in this case, but I can easily write you an example there it fails.

**Comment by konne** [comment]
I think this should work:
```
 [
    {
        type: static
        name: AccountDesc
        values: ['"Audit Fees"']
    }                            
]
```
Why you try to send a selection with SER.START? During onDemand Previde you should use Bookmark / shared Session.

**Comment by mossbeard** [comment]
Is fixed and test. New solution
