### ISSUE TITLE
[BUG] missing style format on next page when use sheetloop

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/senseexcel-reporting#48]
In Sense Excel:  if you use an chart with none default style format it works perfectly!
But if you also use sheetloop in your report.
The report lost on the secound page the style format.

![image](https://user-images.githubusercontent.com/13659581/52768720-905aa800-302e-11e9-8fba-eeb65ad515e2.png)

https://github.com/q2g/ser-engine/issues/63

**Comment by mossbeard** [comment]
Is fixed
