### ISSUE TITLE
[FR] Use multiple User for Hub 

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/senseexcel-reporting#55]
Use multiple User for Hub reports in a report config without loop

![image](https://user-images.githubusercontent.com/13659581/52998915-ba440e00-3424-11e9-92f8-fb5ad0a0d560.png)

**Comment by AlexanderGoerlich** [comment]
[Doku] - solve that with security rules

```
hub: {
...
tags: [a,b,c]

}
```

**Comment by thomashaenig** [comment]
moved to another repo
