### ISSUE TITLE
New algorithm for setting the data source for pivot tables in the sheet loop.

### ISSUE THREAD

**Issue by mossbeard** [senseexcel/senseexcel-reporting#69]
Im Standardfall verweisen alle kopierten Sheets auf den original sheet, was aber nicht immer so gewollt ist.
Da die pivot table nicht die richtigen Daten anzeigt. Diese Sache besprechen wir nochmal genauer, da es kein einfacher Algorithmus ist.

**Comment by thomashaenig** [comment]
fixed with https://github.com/q2g/ser-engine/commit/deb1b4fb91d555e81b93bdddf0336fddda5cc4cc
