### ISSUE TITLE
[Bug] Aspose-Bug with Tablestyle

### ISSUE THREAD

**Issue by ChristofHoldschick** [senseexcel/senseexcel-reporting#75]
When the selected Typestyle is not painted properly, in SER it gets applied correctly, but is not fully painted
the Table in Senseexcel looks like this:
![grafik](https://user-images.githubusercontent.com/35026589/55385494-96004480-552d-11e9-9327-95443eb1a1fb.png)

but in the Report the alternating backcolor of the style isn't applied, the rows remains white:
![grafik](https://user-images.githubusercontent.com/35026589/55385567-be883e80-552d-11e9-9392-d7602b38ae06.png)

**Comment by mossbeard** [comment]
Is fixed
